import { GetStaticProps } from 'next'
import Head from 'next/head'

import client from "../contentful"

const Home = ({ home }: { home: any }) => {

  return (
    <div>
      <Head>
        <title>{home.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{home.fields.title}</h1>
      </main>

    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const home = await client.getEntries({
    content_type: 'home',
    limit: 1,
  });

  const [homePage] = home.items;

  return {
    props: {
      title: 'My blog',
      home: homePage,
    },
    revalidate: 3000,
  };
}
