import { GetStaticProps } from 'next';
import Head from 'next/head';
import { IHome, IHomeFields } from '../contentful';

import client from '../contentful/index';

const Home = ({ home }: { home: IHome }) => {
  return (
    <div>
      <Head>
        <title>{home.fields.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>{home.fields.title}</h1>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const home = await client.getEntries<IHomeFields>({
    content_type: 'home',
    limit: 1,
  });

  const [homePage] = home.items;

  return {
    props: {
      title: 'My blog',
      home: homePage,
    },
    revalidate: 3000,
  };
};
