import { GetStaticProps } from 'next'
import Head from 'next/head'

const Home = ({ title }: { title: string }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{title}</h1>
      </main>

    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  console.log('props');

  return {
    props: {
      title: 'My blog',
    },
    revalidate: 3000,
  };
}
